travis:
  secure:
    BINSTAR_TOKEN: tPUnhPE2+troRdf1exJWzwo9GE9T93Qk0FvQ1a3NvHOenfbknabr6sMKfLl8NJZoJAAWeckd2F/B2w0oqfjQgWqo1WX+BiTJK5et2sNxQJtmrf3VcXVwcKrIPapmZm7BFff/ojjobnlYHc+ONZ32vEPY0GvSZRRLuLPdZE3fbnosMD+ccPs1cZxvVnbxk6rrjAeyOrQYbvCCFUzP0VBNoDRa3uF6jB00P+n4PISh/CTZScKv23vnCZ2m8r1+Ifvb9Jc04PM3khxzTxKhVjVirFbU6cZMSUQ817d/KwzbWcWgMgOeGCz94ukbB7jjbjmy9zcW5pG4us7KZ0Z8fuKWJ78qrZtI2ptwZwDX03c839XWTboC/JkPEfcT0W13MhMCvNihfRQtCdI3q9StQUoHssZN5p67x7ILe2U1HVECw+4X0j0++EJlS8ABYE0PPCzEvwbiLksMHol6zvilj6q9WPKQf7tCedBD8AOeZei4teKV80+iWTik9srVKZNjS5XMOwHQ8JyeYwhKUmRyYvnqyCPhRee7r2Uok39x+UkyJ3F1dhg9xLR5Pt35ymfGxUFzNM8NcT4/voikEZytAPWVkOEMC8s6LA5cbVPrWnFSqbp2YkLRabSijo9h9TIfQB/lBRsWBUuIP3VWkN2AZWAeAtQ9XXtds804LL8LbxPFvSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
